using System.Security.Cryptography;

namespace TicketApi.Services;

// Requirement 11, with the security work that makes file upload safe rather
// than a liability. Every rule here exists because of a real class of attack.

public class AttachmentStorage
{
    private readonly string _root;
    private readonly ILogger<AttachmentStorage> _logger;

    public const long MaxFileSizeBytes = 10 * 1024 * 1024;   // 10 MB

    // A whitelist, never a blacklist. Blacklists always miss something —
    // .php5, .phtml, .svg with embedded script, .html — and one miss is a
    // stored XSS or worse. If it is not on this list, it does not upload.
    private static readonly HashSet<string> AllowedExtensions = new(StringComparer.OrdinalIgnoreCase) {
        ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp",
        ".pdf", ".txt", ".csv", ".log",
        ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
        ".zip"
    };

    public AttachmentStorage(IConfiguration config, ILogger<AttachmentStorage> logger)
    {
        _logger = logger;

        // Outside any directory the web server will serve. This application
        // serves no static files at all, which is the strongest version of
        // that guarantee: an uploaded file simply has no URL.
        _root = config["Storage:AttachmentPath"]
                ?? Path.Combine(AppContext.BaseDirectory, "attachment-store");

        Directory.CreateDirectory(_root);
        _logger.LogInformation("Attachment storage at {Path}", _root);
    }

    public static bool IsAllowed(string fileName, out string reason)
    {
        var ext = Path.GetExtension(fileName);

        if (string.IsNullOrWhiteSpace(ext)) {
            reason = "Files must have an extension.";
            return false;
        }

        if (!AllowedExtensions.Contains(ext)) {
            reason = $"Files of type {ext} are not accepted.";
            return false;
        }

        reason = "";
        return true;
    }

    // Saves the stream and returns the RELATIVE stored path.
    public async Task<string> SaveAsync(Stream input, string originalName,
                                        CancellationToken token = default)
    {
        // The client's filename never touches the filesystem. A name like
        // "../../etc/cron.d/evil" or "..\\..\\Windows\\System32\\x.dll" is a
        // path traversal attack, and sanitising such names correctly on every
        // platform is harder than not using them. We generate our own.
        var ext = Path.GetExtension(originalName).ToLowerInvariant();
        var generated = $"{Guid.NewGuid():N}{ext}";

        // Subdirectory per month: a single folder with 50,000 files is slow
        // to list and unpleasant to back up.
        var subDir = DateTime.UtcNow.ToString("yyyy-MM");
        var fullDir = Path.Combine(_root, subDir);
        Directory.CreateDirectory(fullDir);

        var fullPath = Path.Combine(fullDir, generated);

        await using var output = File.Create(fullPath);
        await input.CopyToAsync(output, token);

        return Path.Combine(subDir, generated);
    }

    // Resolves a stored path to a real file, refusing anything that escapes
    // the storage root. Defence in depth: the paths in the database were all
    // generated by SaveAsync, but if one were ever tampered with, this stops
    // it from reading /etc/passwd.
    public bool TryResolve(string storedPath, out string fullPath)
    {
        fullPath = "";

        var candidate = Path.GetFullPath(Path.Combine(_root, storedPath));
        var rootFull  = Path.GetFullPath(_root);

        if (!candidate.StartsWith(rootFull, StringComparison.Ordinal)) {
            _logger.LogWarning("Rejected path outside storage root: {Path}", storedPath);
            return false;
        }

        if (!File.Exists(candidate))
            return false;

        fullPath = candidate;
        return true;
    }

    public void Delete(string storedPath)
    {
        if (TryResolve(storedPath, out var fullPath))
            File.Delete(fullPath);
    }
}
